services:
  - type: web
    name: tryggpuls
    repo: https://github.com/Blacknapoleon99/pulse-sweden
    branch: demo-polish-release
    region: oregon
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production